:PROPERTIES:
:ID:       920c03cb-bcda-4f16-902c-a37995a5c1d8
:END:
#+title: Eerste Wereldoorlog

Tijdens de eerste wereld oorlog kwam het grote [[id:63346b69-7965-4807-a019-c99ccd76bf68][Ottomaanse Rijk]] aan de kant van Duitsland te vechten.
Engeland zag hier toch wel een probleem in. Om hier wat aan te doen heeft Engeland
tussen 1915 en 1917 drie verschillende akkoorden gesloten:

1 Een verdrag met de Shariff van Mekka
  waarin de creatie van een Arabisch koninkrijk werd geregeld. Als tegenprestatie moest de Sharif
  een opstand onder Arabische bevolking organiseren, waardoor de positie van Duitsland
  aan het wankelen zou komen.
  E.e.a. is georganiseerd door de Engelse McMahon
2 Een verdrag met met Frankrijk voor de verdeling van Syrie en Mesopotamie
  tussen Engeland en Frankrijk en ook de wensen van Rusland wat betreft de Anatolie werden gekend.
  Het finale akkoord werd beldn als het 
3 Een belofte van een staat [[id:d6fd72b5-444e-4be8-8ab5-6777d5ee8ea0][Israel]] in [[id:3198bff9-7a59-4484-8f71-94ff48fb89d0][Palestina]]

BOvenstaande is georganiseerd door de Engelse McMahon


