:PROPERTIES:
:ID:       3198bff9-7a59-4484-8f71-94ff48fb89d0
:END:
#+title: Palestina
#+filetags: :Palestina:

Gebied waar Arabieren en (een weinig) Joden samen leefden.

Na Passfield Whitepaper vertraagde de in-flux van joden naar Palestina

| Start Periode | Eind Periode | Aantal Migranten [/jaar] | Opmerking                                      |
|---------------+--------------+--------------------------+------------------------------------------------|
|          1929 |         1931 |              5000...6000 | Na de [[id:4aeeb49b-4261-4230-a1d9-7aa6f8373a48][Passfield White Paper]]                    |
|          1932 |              |                    10000 | Hitler in Duitsland en [[id:601c730b-335a-4bba-bb41-9f0ae2af710f][Mac-Donald Black Letter]] |
|          1933 |              |                    30000 |                                                |
|          1934 |              |                    42000 |                                                |
|          1935 |              |                    62000 |                                                |
|---------------+--------------+--------------------------+------------------------------------------------|

Tussen 1922 en 1935 steeg de Joodse populatie van +/- 9% naar +/- 27%.

De Joden (nieuwe bewoners in Palestina) kochten significante stukken land, waarmee grote groepen Palestijnen ontheemd werden.
Het is op te merken dat de leiding/regering in Palestina voornamelijk bestond uit rijke "elite" uit
de steden. Deze hadden vrijwel geen oog voor wat er op het platte lang gebeurde.

In 1935 stond [[id:7e37e125-9fa3-49cd-8634-707569dc6bee][Izz al-Din al-Qassam]] op. Na de [[id:601c730b-335a-4bba-bb41-9f0ae2af710f][Mac-Donald Black Letter]] begon hij het idee te promoten van een
geweldadige opstand tegen de Britten en de Zionisten. In 1935 kwam Shaikh al-Wassam in een vuurgevecht samen met een aantal
volgelingen om het leven.
