:PROPERTIES:
:ID:       189b01f6-d06b-4488-84ca-caf9c82886b1
:TIMELINE_START: 1854
:TIMELINE_END: 1863
:END:
#+title: Said Pasha
#+filetags: :Egypte:

Said Pasha was een van de leiders van [[id:6ed4b8a9-f665-4392-a065-68179c59ee8b][Egypte]] Hij regeerde van 1854 tot 1863.

Said Pasha ging verder op hepad van zijn voorganger [[id:26854881-0ce9-4acc-b7ff-7089fa9bed7a][Abbas Pasha]].
Maar hij ging veel verder dan zijn voorganger met concessies aan het buitenland.

- Een tweede spoorlijn tussen Cairo en Alexandria
- Een spoorlijn tussen Cairo en Suez : het Suez Kanaal
- Stoomschepen op de Nijl
- In 1856 gaf hij aan zijn Franse tutor de concessie een waterweg te creeeren tussen Suez en de Rode zee
  - De Britten waren niet erg blij met deze ontwikkeling, omdat hun India-Europe route dan wel heel erg afhankelijk van een kanaal in beheer door de Fransen
  - De Britten konden niet tegen het bouwen op Egyptisch grond ageren, maar wel tegen arbeid tegen 0 tarief, dit lijkt verdacht veel op slavenarbeid.
  - Egypte was in het overige nog sterk afhankelijk vand e Britten dus ze gingen enigszins door de knieen
  - Egypte gaf aan de SCC (Suez Canal Company) aan dat ze de orginele contracten wilden heronderhandlen.
  - Dat vond de (Franse) SCC niet zo grappig en gaf de zaak door aan de Franse regering om de rechten tegenover Engalend veilig te stellenn

  Dit waren niet allemaal even succesvolle ondernemingen. Wanneer er verlies werd geleden vroegen de consuls van de landen om vergoedingen vanwege verlies in waarde van aandelen.
  
